# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cac367d8d2725bba976b47ea59d4ffb07615820ab3beae450e7b8a56331dcf80d182c5fa6542d04f1c4801807b60a17cbc6dfa70b9f3b4ae644b51767c2ff87e

test:
  secret_key_base: e45f238da187830323f4cd7d46437ff2d514a62d2d5cff5116cb8e127bd9ff363e9d37527246c1af07db40740f9c5de0c5b68f5e38be577392ef9ff163384a56

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
